sudo: required
language: go
go:
- '1.14'
services:
- docker
env:
  global:
  - DOCKER_BUILDKIT=1
  - secure: iwo48s9ZW6x1+hncnMlu8/4eCvoawnJiq3x8bnd9TWsgzRegbikmh0asZQ2B8akk39UFzxpDibb1s754KGMxYVwn1Jtdi9y6o/1DTwf4mPNhGUbandSPnO3hbxfzgToWDnNiEhLzZedCdSktSfrAO8JJLiwTVlBr5t240wHTrS8/ZD2eyo8oPKOMZbqLw4DRtHdzaIPUaxSCClnV1+WZLYX8D3uyMM0G1xi7OHBZVF8RaTsVnkRGtIUZeFtcEAWOBmVpRMOVO3giRB57rWvNOPuYUepXAtI6nYfZjLGMVIzxfaLy/loLLkRNHEJin2qDK3X/YP/kMYBxNc3pA73ne4pV1drM5J+raVurDV0IL3NsQ9IU6QRfZ/JkDZ3fbca8Z5gqUapEWZoY7zsbo5+OTNjlWGPNt2DkaWppCdfAolpS7feZLe+9hvH2FwUUBY77utk0v3Dr2lIJzCK7iAjLL8HbXFVMDmOuVr5MdMRu7RBQohVB0buymy8/kW0/GdIUnyUCGymdF2drivPgepqO86fT1Wv/+JRRrV7mShwJNCYM9VteBuwBVziWtapxcr1g9b0iv8Yhvi65eLMCV+y+a3mmKtmCXx6JeobHfVZ1UA6SALZdSzpeJzFRsANGn+eBdaXPslONmE1ZKV5YsFroVYFD5rRftOHRkV8I/EmHV5w=
  - secure: Nmr0MF6RxTEMRwTiFzlmdtZok8mPvNiF5GCQzrucTrzXwpAW85Bzu7M45137chP3gvsZokjel3s3diTYGpc81tPy3jf3gTE3Ba48Y4lxNiSPQC+Z4Iie9ZkPm46bTdN3Sg8c2/5tWJB/7dxYBKRhNzoE6sIt9nrTF6s1mVMmqWfe21bntiRTLoOM0zuUQQ3Y8AQSFHtfbn2GBl+wWpGGiyWLi2sYTL9KZgGwbjj1tL6QS+F9VOc1n+ARCvA5LOdhk6R1N6x1xsYy8EXMqFHxooXE5o6zdAZ+Xd9KPaKKXzlQMGJIhmnRJkAKkeCJNHYwCjiUlyptQncpxRwyRWac853LnbGAcTPLt8n2PyUikCWK/zOoCMFbdb7AX8cUxLn1U/z8XIk8RN6uuvUm3NKQLsK+F9ydc94yUfg/1JhuzqbU9gX+KhYRbtNLe6ummYoi0vknZP74dWi0ju/4iXFuo1UULDVtmn7uy91tMZ1pdnOqHjUB5CapTgPSNm4Lhhz1MFyM2GZy7TRWJ76zxFfvjEzvpEsAsV4HZCLguAqXvyX55L633M99W00nG+99RgDlSN00DkJUE/Tkrr+KNm5GZKJT5pE7oJXk11bAiNldM9FoWuAGKUuk1aR7KfZNGX+A9n0b8lJhkV3OAeorv9GClIYU6YW7z/wyrS2qg1SjNKo=
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get install socat
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- |
  echo '{"mtu": 1460}' | sudo tee /etc/docker/daemon.json
  sudo systemctl restart docker
- make install-deps
script:
- make test
deploy:
- provider: script
  skip_cleanup: true
  script: make skaffold.push
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
