---
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "github-team-approver.labels" . | indent 4 }}
  name: {{ include "github-team-approver.fullname" . }}
  namespace: {{ include "github-team-approver.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "github-team-approver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
