---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "github-team-approver.labels" . | indent 4 }}
  name: {{ include "github-team-approver.fullname" . }}
  namespace: {{ include "github-team-approver.namespace" . }}
